name: PythonMCSchool
main: me.bluenitrox.school.SchoolMode
description: "This is a Plugin of two German programmers."
authors: [1BlueNitrox - Daarkii]
version: 2.0.1

commands:
  set:
    description: "This Command set a Location if you want"
    aliases:
      - setlocation
  money:
    description: "This Command update your balance"
    aliases:
      - balance
      - konto
      - kontostand
      - geld
      - gems
      - gem
  gm:
    description: "This Command set you or a Player in the Gamemode 0/1/2/3. Usage: /gm <1/2/3/0> [Player]"
    aliases:
      - gamemode
  heal:
    description: "This Command heal you or a Player. Usage: /heal [Player]"
  feed:
    description: "This Command feeds you or a Player. Usage: /feed [Player]"
  fly:
    description: "This Command set you or a Player in the Flymode. Usage: /fly [Player]"
    aliases:
      - fliegen
  test:
  getRunen:
  wb:
    aliases:
      - workbench
      - werkbank
  taxi:
  schmied:
    aliases:
      - smith
      - sm
  testzwei:
  blocks:
  mymine:
  myangelmine:
    aliases:
      - myangel
  getcases:
  skill:
  tp:
  tphere:
  kit:
  restart:
  stop:
    aliases:
      - neustart
  pet:
    aliases:
      - pets
      - haustier
      - haustiere
      - tier
      - tiere
  exp:
    aliases:
      - level
      - xp
      - erfahrung
      - levelup
  booster:
    aliases:
      - boost
  spawn:
  invsee:
  clear:
  tk:
  plotworld:
    aliases:
      - pw
      - plotwelt
  vanish:
    aliases:
      - v
  books:
  prestige:
  setlevel:
  ah:
    aliases:
      - auktionshaus
      - auctionhouse
      - trade
      - house
      - haus
  build:
    aliases:
      - bauen
  mine:
    aliases:
      - minen
  sell:
    aliases:
      - verkaufen
      - sells
      - händler
  mülleimer:
    aliases:
      - trash
      - müll
  getBooks:
  pl:
    aliases:
      - plugin
      - plugins
      - pls
  stats:
  dungeon:
  DungeonInventory:
  kopfgeld:
  giveSchoolXP:
  testsummon:
  angelmine:
  anvil:
    aliases:
      - amboss
      - av
  enchanter:
    aliases:
      - zaubertisch
  gemlimit:
    aliases:
      - gl
  aufgaben:
    aliases:
      - task
      - tasks
  createnpc:
    aliases:
      - task
      - tasks
  school:
  itemspawner:
  minensettings:
    aliases:
      - ms
  plot:
  wz:
    aliases:
      - warzone
      - kampfzone